apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: service1-pv-claim
  namespace: ns-name1
  labels:
    app: service1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: service2-pv-claim
  namespace: ns-name2
  labels:
    app: service2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
